### ISSUE TITLE
Missing wordpress functions

### ISSUE THREAD

**Issue by jcvignoli** [skaut/wordpress-stubs#61]
Hi there,

Please find a list of missing WP functions I am using:

_get_cron_array()
comments_popup_link
content_url()
delete_post_meta()
did_action()
do_meta_boxes()
edit_post_link()
get_submit_button()
get_terms()
get_the_term_list()
has_block()
has_tag()
have_posts()
number_format_i18n()
register_taxonomy()
request_filesystem_credentials()
single_tag_title()
site_url()
status_header()
the_category()
the_excerpt()
the_ID()
the_permalink() 
the_post()
the_tags()
the_time()
unregister_taxonomy()
unzip_file()
wp_add_inline_script()
wp_delete_term()
wp_deregister_script()
WP_Filesystem()
wp_footer()
wp_get_referer()
wp_head()
wp_kses()
wp_meta()
wp_mkdir_p()
wp_next_scheduled()
wp_remote_fopen()
wp_safe_remote_get()
wp_schedule_single_event()
wp_script_is()
wp_sprintf()
wp_unschedule_event()

Thanks!

**Comment by marekdedic** [comment]
Hi,
thanks for the report. As it's outlined in the readme, this package is hand-created, so some functions may be missing. If you submit a PR, I'd push out a new release once it's merged...
